/**
 * GAME CONFIGURATION
 */
export const CONFIG = {
    TOTAL_LEVELS: 15,
    BASE_SCORE: 10,
    COMBO_BONUS: 5,
    PARTICLE_COUNT: 100,
    ANIMATION_DELAY: 0.1,
    FEEDBACK_DURATION: 1200,
    INITIAL_LIVES: 3
};
